name: UML Editor Angular Web components CI (Lint, Test)

on:
  # push only for branches (ignore tags)
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"
  # pull request only for branches (ignore tags)
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./uml-editor"

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm run lint
      - name: Test Code
        run: npm test
